CREATE DATABASE shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;;

CREATE USER 'shop'@'%' IDENTIFIED BY 'wP9V2vMpmU1Kc8SMJw2U';
-- GRANT ALL ON shop.* TO 'shop'@'%' IDENTIFIED BY 'wP9V2vMpmU1Kc8SMJw2U';
-- DROP USER 'shop'@'%';

-- GRANT ACCESS TO ALL DATABASES AND TABLES
-- GRANT ALL PRIVILEGES ON *.* TO 'shop'@'localhost';

-- GRANT ACCESS TO SHOP DB AND ALL TABLES
-- GRANT ALL PRIVILEGES ON shop.* TO 'shop'@'localhost';
GRANT ALL PRIVILEGES ON shop.* TO 'shop'@'%';

FLUSH PRIVILEGES;

